version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cybertwin_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: cybertwin_dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true